### ISSUE TITLE
Make binaries / release

### ISSUE THREAD

**Issue by talaviram** [yairchu/svg-simplify#1]
For those who aren't using haskell daily or have it installed.
Would be nice to use github actions and have releases:

* Linux x64 / amrfh, AArch64
* Windows x64 / x86
* macOS x64

**Comment by phpmoli** [comment]
Can someone share a binary with me? Compilation failed on my machine with only this message: `Process exited with code: ExitFailure 1` (step 46/54) and no more details about it.

Edit: Preferably for Intel [Goldmont](https://en.wikipedia.org/wiki/Goldmont) CPU, if that matters. Or if that is hard, then Intel [Skylake](https://en.wikipedia.org/wiki/Skylake_(microarchitecture)).

Edit: also, the `.stack` directory is 3GB, which is massive for just compiling this tool.

**Comment by yairchu** [comment]
> Can someone share a binary with me?

Which OS?

> Compilation failed on my machine with only this message: `Process exited with code: ExitFailure 1` (step 46/54) and no more details about it.

Aren't there any details above it on which process exited or why?

> Edit: also, the `.stack` directory is 3GB, which is massive for just compiling this tool.

I'm afraid that's just [due to my choice of using Haskell](https://www.reddit.com/r/haskell/comments/en51y2/huge_stack_after_installation/). Hopefully providing binaries will help people avoid wasting their disk space

**Comment by phpmoli** [comment]
Thanks for the reply!

I'm sorry i forgot the OS, Debian Linux bullseye x86_64.

I do not want to hijack this issue with an unrelated issue, because after your reply, i dug into this more and gathered more data, so i opened issue #4 which has more details about my problem above. Sorry, thanks.

**Comment by yairchu** [comment]
@phpmoli Does the new [ubuntu executable built on GitHub actions](https://github.com/yairchu/svg-simplify/releases/tag/v0.1.0.0) work for you on Debian?

**Comment by phpmoli** [comment]
Thanks! Running the binary says:

```
./svg-simplify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./svg-simplify)
./svg-simplify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./svg-simplify)
```

`apt-show-versions libc6` says:
```
libc6:amd64/bullseye 2.31-13+deb11u5 uptodate
```

Because Ubuntu is forked from the unstable debian-sid version.

**Comment by yairchu** [comment]
Even though it doesn't solve the problem universally (i.e Debian as noted above), this is done with https://github.com/yairchu/svg-simplify/releases/tag/v0.1.0.0
